### ISSUE TITLE
A question about the test dataset

### ISSUE THREAD

**Issue by ericyinyzy** [xijia-tao/ImgTrojan#1]
Hi! 
I am interested in which test dataset is used in this project.  I have double-checked the paper and codes but didn't find details about the test data. Is it evaluated on Advbench or Realtoxicity?  Thanks!

**Comment by xijia-tao** [comment]
Hi! Thank you for your interest.
For attack success rate (ASR), we manually curated a list of harmful queries that are more likely to be refused by models. They are provided [here](https://github.com/xijia-tao/ImgTrojan/tree/main/evaluation/attack_rate_metric/poison/ref/sensitive_inputs.txt). 

We will try to benchmark ImgTrojan on Advbench you mentioned in our future updates. For Realtoxicity, I believe it does not fit into our method's use case as it provides toxic prompts instead of harmful instructions to be followed. Thanks!

**Comment by ericyinyzy** [comment]
Thanks a lot! I expect it can be evaluated using more generalized toxic data. Thanks!
